# Generated by Django 3.0.3 on 2020-03-21 05:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20200313_0253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contagionsite',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='contagionsite',
            name='start_time',
        ),
        migrations.AddField(
            model_name='confirmedcase',
            name='date_first_symptoms',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date of first symptoms'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contagionsite',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='end time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contagionsite',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='start time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='confirmedcase',
            name='date_confirmed',
            field=models.DateField(verbose_name='date confirmed'),
        ),
        migrations.AlterField(
            model_name='confirmedcase',
            name='estimated_date_contracted',
            field=models.DateField(verbose_name='estimated date contracted'),
        ),
        migrations.CreateModel(
            name='MedicalDatum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unknown', "I don't know")], max_length=255)),
                ('confirmed_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.ConfirmedCase')),
            ],
        ),
    ]
